# Generated by Django 5.2.10 on 2026-02-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_year', models.IntegerField(unique=True)),
                ('payroll_start', models.DateField()),
                ('payroll_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('semi-monthly', 'Semi-Monthly'), ('monthly', 'Monthly'), ('quadriweekly', 'Quadriweekly'), ('daily', 'Daily')], max_length=50)),
                ('first_day', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('second_day', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
