# Generated by Django 5.2.10 on 2026-02-11 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollinfo',
            options={'verbose_name': 'Payroll Info', 'verbose_name_plural': 'Payroll Info'},
        ),
    ]
