# Generated by Django 5.2.10 on 2026-02-04 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('confirmed', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.location')),
            ],
            options={
                'verbose_name': 'Calendar Entry',
                'verbose_name_plural': 'Calendar Entries',
            },
        ),
    ]
