# Generated by Django 5.2.10 on 2026-04-16 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_calendarentry'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarentry',
            name='entry_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('vacation', 'Vacation'), ('sick', 'Sick'), ('holiday', 'Holiday'), ('floating_holiday', 'Floating Holiday'), ('personal', 'Personal'), ('overtime', 'Overtime'), ('swap', 'Shift Swap')], default='scheduled', max_length=50),
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='calendarentry',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='calendarentry',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.location'),
        ),
        migrations.AlterField(
            model_name='calendarentry',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='staff.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.location')),
            ],
            options={
                'verbose_name': 'Schedule Template',
                'verbose_name_plural': 'Schedule Templates',
            },
        ),
    ]
