# Generated by Django 5.2.10 on 2026-05-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_calendarentry_entry_type_notes_scheduletemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarentry',
            name='break_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='break_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
