# Generated by Django 5.2.10 on 2026-05-04 15:56

from django.db import migrations, models

DEFAULT_ENTRY_TYPES = [
    ("Floating Holiday", "FLH"),
    ("Holiday", "HOL"),
    ("Overtime", "OVT"),
    ("Personal", "PER"),
    ("Scheduled", "SCH"),
    ("Shift Swap", "SWP"),
    ("Sick", "SIC"),
    ("Vacation", "VAC"),
]

LEGACY_TO_CODE = {
    "scheduled": "SCH",
    "vacation": "VAC",
    "sick": "SIC",
    "holiday": "HOL",
    "floating_holiday": "FLH",
    "personal": "PER",
    "overtime": "OVT",
    "swap": "SWP",
}


def seed_entry_types_and_remap(apps, schema_editor):
    EntryType = apps.get_model("planner", "EntryType")
    CalendarEntry = apps.get_model("planner", "CalendarEntry")

    for name, code in DEFAULT_ENTRY_TYPES:
        EntryType.objects.get_or_create(code=code, defaults={"name": name})

    for entry in CalendarEntry.objects.all():
        code = LEGACY_TO_CODE.get(entry.entry_type)
        if code and entry.entry_type != code:
            entry.entry_type = code
            entry.save(update_fields=["entry_type"])


def reverse_remap(apps, schema_editor):
    pass  # data-only reverse is a no-op


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_break_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='calendarentry',
            name='entry_type',
            field=models.CharField(default='SCH', max_length=10),
        ),
        migrations.RunPython(seed_entry_types_and_remap, reverse_remap),
    ]
