version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.combined
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - logs_volume:/home/app/web/logs
      - postgres_bkp:/backups/
    ports:
      - 7000:80
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - TZ=${TIMEZONE}
    image: lenoreschedule:production
    container_name: lenoreschedule_app
    restart: unless-stopped

  db:
    image: postgres:18-trixie
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    container_name: lenoreschedule_db
    environment:
      - TZ=UTC
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
  logs_volume:
  postgres_bkp:
