# Generated by Django 5.2.10 on 2026-01-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=100, unique=True)),
                ('rule_type', models.CharField(choices=[('fixed_date', 'Fixed date'), ('nth_weekday', 'Nth weekday of month'), ('last_weekday', 'Last weekday of month'), ('custom', 'Custom rule')], max_length=50)),
                ('month', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('day', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('week', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('observed_rule', models.CharField(choices=[('none', 'No observation'), ('next_business_day', 'Next business day'), ('nearest_weekday', 'Nearest weekday')], default='none', max_length=50)),
            ],
        ),
    ]
